// Build scripts report failure by panicking, which is idiomatic and cannot
// propagate a `Result`; exempt them from the crate-wide panic-safety lints.
#![allow(clippy::panic, clippy::unwrap_used, clippy::expect_used)]

use std::path::Path;
use std::{env, fs};

use lt_schema_codegen::{
    AllowlistConfig, extract_input_object_fields, format_generated, gen_parse_sort_value,
    gen_parser_fn, gen_stem_key_enum, gen_stem_kind_enum, validate_filter_fields,
    validate_sort_fields,
};
use proc_macro2::TokenStream;
use quote::quote;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let manifest = Path::new(&manifest_dir);
    let schema_path = manifest.join("../../build/linear-schema-definition.graphql");

    // Tell cargo to re-run this script when these files change.
    println!("cargo:rerun-if-changed={}", schema_path.display());
    println!(
        "cargo:rerun-if-changed={}",
        manifest
            .join("../../build/search_filter_fields.toml")
            .display()
    );
    println!("cargo:rerun-if-changed=build.rs");

    // -----------------------------------------------------------------------
    // Load the allowlist
    // -----------------------------------------------------------------------
    let toml_path = manifest.join("../../build/search_filter_fields.toml");
    let toml_src = fs::read_to_string(&toml_path)
        .unwrap_or_else(|e| panic!("Cannot read allowlist at {}: {e}", toml_path.display()));
    let config: AllowlistConfig = toml::from_str(&toml_src).unwrap_or_else(|e| {
        panic!(
            "Failed to parse allowlist TOML at {}: {e}",
            toml_path.display()
        )
    });

    // -----------------------------------------------------------------------
    // Load and parse the GraphQL schema
    // -----------------------------------------------------------------------
    let schema_src = fs::read_to_string(&schema_path).unwrap_or_else(|e| {
        panic!(
            "Cannot read GraphQL schema at {}: {e}",
            schema_path.display()
        )
    });
    let issue_filter_fields = extract_input_object_fields(&schema_src, "IssueFilter");
    let issue_sort_input_fields = extract_input_object_fields(&schema_src, "IssueSortInput");

    // -----------------------------------------------------------------------
    // Validate every filter allowlist entry against the schema
    // -----------------------------------------------------------------------
    validate_filter_fields(&config.field, &issue_filter_fields);
    validate_sort_fields(&config.sort_field, &issue_sort_input_fields);

    let sort_fields = &config.sort_field;

    // -----------------------------------------------------------------------
    // Generate search_stems.rs
    // -----------------------------------------------------------------------
    let fields = &config.field;

    let stem_key_enum = gen_stem_key_enum(fields);
    let stem_kind_enum = gen_stem_kind_enum(fields);
    let parse_sort_value_fn = gen_parse_sort_value(sort_fields);
    let parser_fn = gen_parser_fn(fields);

    // Combine all fragments into a single TokenStream.
    // parse_sort_value must come before parser_fn, which calls it.
    let combined: TokenStream = quote! {
        #stem_key_enum
        #stem_kind_enum
        #parse_sort_value_fn
        #parser_fn
    };

    let file_header = "// search_stems.rs -- generated by build.rs (bd-117, bd-2w5)\n\
                       // DO NOT EDIT -- regenerate by running `cargo build`\n\n";
    let out_src = format_generated(file_header, combined);

    let stems_path = Path::new(&out_dir).join("search_stems.rs");
    fs::write(&stems_path, &out_src)
        .unwrap_or_else(|e| panic!("Cannot write {}: {e}", stems_path.display()));
}
