// Build scripts report failure by panicking, which is idiomatic and cannot
// propagate a Result; the crate-wide panic-safety lints do not apply here.
#![allow(clippy::expect_used, clippy::unwrap_used, clippy::panic)]

use std::path::Path;
use std::{env, fs};

use lt_schema_codegen::{
    AllowlistConfig, extract_input_object_fields, format_generated, gen_build_sort,
    gen_sort_field_enum, validate_sort_fields,
};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let manifest = Path::new(&manifest_dir);
    let schema_path = manifest.join("../../build/linear-schema-definition.graphql");
    let toml_path = manifest.join("../../build/search_filter_fields.toml");

    // Tell cargo to re-run this script when these files change.
    println!("cargo:rerun-if-changed={}", schema_path.display());
    println!("cargo:rerun-if-changed={}", toml_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    // Make the snapshot available to `#[cynic::schema("linear")]` and the
    // `QueryFragment` derives, which read it from `$OUT_DIR/cynic-schemas`.
    cynic_codegen::register_schema("linear")
        .from_sdl_file(&schema_path)
        .expect("registering Linear schema with cynic")
        .as_default()
        .expect("setting cynic default schema");

    // -----------------------------------------------------------------------
    // Load the allowlist
    // -----------------------------------------------------------------------
    let toml_src = fs::read_to_string(&toml_path)
        .unwrap_or_else(|e| panic!("Cannot read allowlist at {}: {e}", toml_path.display()));
    let config: AllowlistConfig = toml::from_str(&toml_src).unwrap_or_else(|e| {
        panic!(
            "Failed to parse allowlist TOML at {}: {e}",
            toml_path.display()
        )
    });

    // -----------------------------------------------------------------------
    // Load and parse the GraphQL schema, validate sort fields
    // -----------------------------------------------------------------------
    let schema_src = fs::read_to_string(&schema_path).unwrap_or_else(|e| {
        panic!(
            "Cannot read GraphQL schema at {}: {e}",
            schema_path.display()
        )
    });
    let issue_sort_input_fields = extract_input_object_fields(&schema_src, "IssueSortInput");

    validate_sort_fields(&config.sort_field, &issue_sort_input_fields);

    let sort_fields = &config.sort_field;

    // -----------------------------------------------------------------------
    // Generate sort_field.rs  (included in src/query.rs)
    // -----------------------------------------------------------------------
    let sort_field_header = "// sort_field.rs -- generated by build.rs (bd-2w5)\n\
                             // DO NOT EDIT -- regenerate by running `cargo build`\n\n";
    let sort_field_src = format_generated(sort_field_header, gen_sort_field_enum(sort_fields));

    let sort_field_path = Path::new(&out_dir).join("sort_field.rs");
    fs::write(&sort_field_path, &sort_field_src)
        .unwrap_or_else(|e| panic!("Cannot write {}: {e}", sort_field_path.display()));

    // -----------------------------------------------------------------------
    // Generate sort_build.rs  (included in src/query.rs)
    // -----------------------------------------------------------------------
    let sort_build_header = "// sort_build.rs -- generated by build.rs (bd-2w5)\n\
                             // DO NOT EDIT -- regenerate by running `cargo build`\n\n";
    let sort_build_src = format_generated(sort_build_header, gen_build_sort(sort_fields));

    let sort_build_path = Path::new(&out_dir).join("sort_build.rs");
    fs::write(&sort_build_path, &sort_build_src)
        .unwrap_or_else(|e| panic!("Cannot write {}: {e}", sort_build_path.display()));
}
