name: ci

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build
    runs-on: namespace-profile-cached-amd64-lg
    steps:
      - uses: actions/checkout@v6
      - uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            /nix
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            accept-flake-config = true
      - run: nix build .#lt
      - run: nix develop .#lt --command cargo check
      - run: nix develop .#lt --command cargo test
