//! Team metadata: the team list, a team's workflow states (Linear's stored
//! `position` order), and its memberships. The sync cycle owns
//! `workflow_states`: it fetches every team, then every workflow state across
//! every team (`AllWorkflowStatesQuery`), before any issue page, so an issue's
//! `state_id` always references an already-known row.

use anyhow::{Context, Result};
use lt_upstream::query::types;
use lt_upstream::query::types::{User, WorkflowState};
use rusqlite::{Connection, params};

use crate::db::crud::Insert;
use crate::db::sql::{self, Sql};

/// Ensure a skeleton team row exists (empty-string placeholder name) so a
/// team-scoped state FK holds; a later [`upsert_teams`] names it.
pub(crate) fn mint_team(conn: &Connection, id: &str) -> Result<()> {
    sql::execute(conn, sql::MINT_TEAM, params![id], "mint team skeleton")
}

/// Upsert one workflow state scoped to its team, with Linear's stored
/// position. Mints the team first (a skeleton row if not yet cached) so the
/// state's `team_id` FK always holds.
pub fn upsert_team_state(conn: &Connection, team_id: &str, state: &WorkflowState) -> Result<()> {
    mint_team(conn, team_id)?;
    sql::execute(
        conn,
        sql::UPSERT_WORKFLOW_STATE_SCOPED,
        params![state.id.inner(), state.name, team_id, state.position],
        "upsert team-scoped workflow state",
    )
}

/// Generates `pub fn $fn_name(conn, entities: &[$ty]) -> Result<()>`,
/// upserting each entity via its generated [`Insert`] impl. A declarative
/// macro rather than a shared generic helper, so the near-identical typed
/// wrappers ([`upsert_teams`], [`upsert_users`]) don't trip `cargo dupes`.
macro_rules! upsert_entities_fn {
    ($fn_name:ident, $doc:expr, $ty:ty) => {
        #[doc = $doc]
        pub fn $fn_name(conn: &Connection, entities: &[$ty]) -> Result<()> {
            for entity in entities {
                entity.insert(conn)?;
            }
            Ok(())
        }
    };
}

upsert_entities_fn!(
    upsert_teams,
    "Upsert fetched teams into the `teams` table.",
    types::Team
);
upsert_entities_fn!(
    upsert_users,
    "Upsert fetched users into the `users` table, so a team-membership join resolves names.",
    types::User
);

/// Run a registered `(id, name)`-shaped `SELECT` -- the shared shape behind
/// [`query_teams`] and the team-scoped queries generated by
/// `query_team_scoped_fn!` below.
fn query_id_name_rows(
    conn: &Connection,
    stmt_sql: Sql,
    params: impl rusqlite::Params,
) -> Result<Vec<(String, String)>> {
    let mut stmt =
        sql::prepare(conn, stmt_sql).context("failed to prepare id/name query statement")?;
    let rows = stmt
        .query_map(params, |row| Ok((row.get("id")?, row.get("name")?)))
        .context("failed to execute id/name query")?;
    let mut out = Vec::new();
    for row in rows {
        out.push(row.context("failed to read id/name row")?);
    }
    Ok(out)
}

/// Every team, alphabetically by name.
pub fn query_teams(conn: &Connection) -> Result<Vec<types::Team>> {
    Ok(query_id_name_rows(conn, sql::QUERY_TEAMS, [])?
        .into_iter()
        .map(|(id, name)| types::Team {
            id: id.into(),
            name,
        })
        .collect())
}

/// Generates `pub fn $fn_name(conn, team_id: &str) -> Result<Vec<$ty>>`, a
/// team-scoped `(id, name)` query. A declarative macro rather than a shared
/// generic helper, so the near-identical typed wrapper ([`query_team_members`])
/// doesn't trip `cargo dupes`.
macro_rules! query_team_scoped_fn {
    // `$ty` is an `ident` fragment (not `ty`/`path`): those fragments are
    // captured as opaque, already-parsed nodes that a following `{` cannot
    // graft onto for a struct literal; a bare `ident` stays reparseable.
    ($fn_name:ident, $doc:expr, $sql:expr, $ty:ident) => {
        #[doc = $doc]
        pub fn $fn_name(conn: &Connection, team_id: &str) -> Result<Vec<$ty>> {
            Ok(query_id_name_rows(conn, $sql, params![team_id])?
                .into_iter()
                .map(|(id, name)| $ty {
                    id: id.into(),
                    name,
                })
                .collect())
        }
    };
}

query_team_scoped_fn!(
    query_team_members,
    "A team's members, resolved through `team_memberships`, by name.",
    sql::QUERY_TEAM_MEMBERS,
    User
);

/// A team's workflow states with Linear's stored `position`, in Linear's
/// stored order.
pub fn query_team_states(conn: &Connection, team_id: &str) -> Result<Vec<WorkflowState>> {
    crate::db::query_rows_id_name_and(
        conn,
        (sql::QUERY_TEAM_STATES, "position"),
        params![team_id],
        |id, name, position| WorkflowState {
            id: id.into(),
            name,
            position,
        },
    )
}

/// Replace a team's membership set with `user_ids`: delete then insert in one
/// transaction, so a member no longer on the team is removed rather than left
/// stale. Mints the team first (a skeleton row if not yet cached) so the
/// membership rows' `team_id` FK always holds.
pub fn replace_team_memberships(conn: &Connection, team_id: &str, user_ids: &[&str]) -> Result<()> {
    let tx = conn
        .unchecked_transaction()
        .context("failed to begin membership replace transaction")?;
    mint_team(&tx, team_id)?;
    sql::execute(
        &tx,
        sql::DELETE_TEAM_MEMBERSHIPS_FOR_TEAM,
        params![team_id],
        "clear team memberships",
    )?;
    for user_id in user_ids {
        sql::execute(
            &tx,
            sql::INSERT_TEAM_MEMBERSHIP,
            params![team_id, user_id],
            "insert team membership",
        )?;
    }
    tx.commit().context("failed to commit membership replace")?;
    Ok(())
}

/// Derive `team_memberships` from the seeded issues' distinct team/assignee
/// and team/creator pairs (`lt sim`; ADR "Sim compatibility" -- there is no
/// real team-membership API to seed from offline).
pub fn derive_team_memberships_from_issues(conn: &Connection) -> Result<()> {
    sql::execute(
        conn,
        sql::DERIVE_TEAM_MEMBERSHIPS_FROM_ISSUES,
        [],
        "derive team memberships from issues",
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::{Storage, op_log};

    fn test_db() -> Connection {
        let db = crate::db::Memory::new().unwrap();
        db.connect().unwrap()
    }

    /// `state` is `(id, name, position)`, grouped so the helper stays under
    /// clippy's `too-many-arguments` threshold.
    fn upsert_state(conn: &Connection, team_id: &str, state: (&str, &str, f64)) {
        let (id, name, position) = state;
        upsert_team_state(
            conn,
            team_id,
            &WorkflowState {
                id: id.into(),
                name: name.to_string(),
                position,
            },
        )
        .unwrap();
    }

    #[test]
    fn query_teams_returns_alphabetical() {
        let conn = test_db();
        upsert_teams(
            &conn,
            &[
                types::Team {
                    id: "z".into(),
                    name: "Zulu".to_string(),
                },
                types::Team {
                    id: "a".into(),
                    name: "Alpha".to_string(),
                },
            ],
        )
        .unwrap();
        let teams = query_teams(&conn).unwrap();
        assert_eq!(
            teams.iter().map(|t| t.name.as_str()).collect::<Vec<_>>(),
            ["Alpha", "Zulu"]
        );
    }

    #[test]
    fn query_team_states_orders_by_position_then_name() {
        let conn = test_db();
        upsert_state(&conn, "t1", ("s-todo", "Todo", 1.0));
        upsert_state(&conn, "t1", ("s-done", "Done", 2.0));
        // Equal position: tie-broken by name.
        upsert_state(&conn, "t1", ("s-zeta", "Zeta", 3.0));
        upsert_state(&conn, "t1", ("s-alpha", "Alpha", 3.0));
        // A different team's state must not leak in.
        upsert_state(&conn, "t2", ("s-other", "Other", 0.5));

        let states = query_team_states(&conn, "t1").unwrap();
        assert_eq!(
            states.iter().map(|s| s.name.as_str()).collect::<Vec<_>>(),
            ["Todo", "Done", "Alpha", "Zeta"]
        );
    }

    #[test]
    fn scoped_upsert_overwrites_position_with_the_latest_write() {
        let conn = test_db();
        upsert_state(&conn, "t1", ("s1", "Todo", 3.5));
        // A later upsert of the same state (e.g. Linear reordered it) replaces
        // the position outright -- no merge against the stored value.
        upsert_state(&conn, "t1", ("s1", "Todo", 4.5));

        let position: f64 = conn
            .query_row(
                "SELECT position FROM workflow_states WHERE id = 's1'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(position.to_bits(), 4.5_f64.to_bits());
    }

    #[test]
    fn replace_team_memberships_is_replace_set() {
        let conn = test_db();
        upsert_users(
            &conn,
            &[
                types::User {
                    id: "u1".into(),
                    name: "Ada".to_string(),
                },
                types::User {
                    id: "u2".into(),
                    name: "Grace".to_string(),
                },
            ],
        )
        .unwrap();

        replace_team_memberships(&conn, "t1", &["u1", "u2"]).unwrap();
        let members = query_team_members(&conn, "t1").unwrap();
        assert_eq!(
            members.iter().map(|u| u.name.as_str()).collect::<Vec<_>>(),
            ["Ada", "Grace"]
        );

        // A second sync with a smaller set drops the removed member instead
        // of leaving it stale.
        replace_team_memberships(&conn, "t1", &["u1"]).unwrap();
        let members = query_team_members(&conn, "t1").unwrap();
        assert_eq!(
            members.iter().map(|u| u.name.as_str()).collect::<Vec<_>>(),
            ["Ada"]
        );
    }

    /// `upsert_team_state` mints a skeleton team row (`name IS NULL`) for a
    /// team never itself fetched; `query_teams` must exclude it until
    /// `upsert_teams` names it.
    #[test]
    fn skeleton_team_is_excluded_from_query_teams_until_named() {
        let conn = test_db();
        upsert_state(&conn, "t1", ("s1", "Todo", 1.0));

        assert!(query_teams(&conn).unwrap().is_empty());

        upsert_teams(
            &conn,
            &[types::Team {
                id: "t1".into(),
                name: "Team One".to_string(),
            }],
        )
        .unwrap();

        let teams = query_teams(&conn).unwrap();
        assert_eq!(
            teams.iter().map(|t| t.name.as_str()).collect::<Vec<_>>(),
            ["Team One"]
        );
    }

    #[test]
    fn derive_team_memberships_from_issues_covers_assignee_and_creator() {
        let conn = test_db();
        let mut issue = op_log::sample_base_issue("1");
        issue.team = types::Team {
            id: "ENG".into(),
            name: "Engineering".to_string(),
        };
        issue.assignee = Some(types::User {
            id: "u-assignee".into(),
            name: "Assignee".to_string(),
        });
        issue.creator = Some(types::User {
            id: "u-creator".into(),
            name: "Creator".to_string(),
        });
        // Sync owns workflow states -- the fixture issue's state must already
        // be locally known for its upsert's foreign key to resolve.
        upsert_team_state(&conn, "ENG", &issue.state).unwrap();
        crate::db::upsert_issues(&conn, &[issue]).unwrap();

        derive_team_memberships_from_issues(&conn).unwrap();

        let members = query_team_members(&conn, "ENG").unwrap();
        let mut names: Vec<&str> = members.iter().map(|u| u.name.as_str()).collect();
        names.sort_unstable();
        assert_eq!(names, ["Assignee", "Creator"]);
    }
}
