//! Team metadata: the team list, a team's workflow states (Linear's stored
//! `position` order), and its memberships. The sync cycle owns
//! `workflow_states`: it fetches every team, then every workflow state across
//! every team (`AllWorkflowStatesQuery`), before any issue page, so an issue's
//! `state_id` always references an already-known row.

use anyhow::{Context, Result};
use lt_types::members::{TeamMembersQuery, UserConnection};
use lt_types::new_issue::{NewIssueData, NewIssueQuery};
use lt_types::states::{AllWorkflowStatesQuery, TeamStatesQuery, WorkflowStateConnection};
use lt_types::teams::{TeamConnection, TeamsQuery};
use lt_types::types;
use lt_types::types::{User, WorkflowState};
use rusqlite::{Connection, params};

use crate::db::ops::{Mutation, Query};
use crate::db::sql::{self, EntityTable, Sql};

/// Upsert one workflow state scoped to its team, with Linear's stored
/// position.
pub fn upsert_team_state(conn: &Connection, team_id: &str, state: &WorkflowState) -> Result<()> {
    sql::execute(
        conn,
        sql::UPSERT_WORKFLOW_STATE_SCOPED,
        params![state.id.inner(), state.name, team_id, state.position],
        "upsert team-scoped workflow state",
    )
}

/// Generates `pub fn $fn_name(conn, entities: &[$ty]) -> Result<()>`,
/// upserting each entity's `(id, name)` into `$table`. A declarative macro
/// rather than a shared generic helper, so the near-identical typed wrappers
/// ([`upsert_teams`], [`upsert_users`]) don't trip `cargo dupes` -- the same
/// reason `sql::entity_upsert_sql!` exists.
macro_rules! upsert_entities_fn {
    ($fn_name:ident, $doc:expr, $table:expr, $ty:ty) => {
        #[doc = $doc]
        pub fn $fn_name(conn: &Connection, entities: &[$ty]) -> Result<()> {
            for entity in entities {
                crate::db::issues::upsert_named_entity(
                    conn,
                    $table,
                    entity.id.inner(),
                    Some(&entity.name),
                )?;
            }
            Ok(())
        }
    };
}

upsert_entities_fn!(
    upsert_teams,
    "Upsert fetched teams into the `teams` table.",
    EntityTable::Teams,
    types::Team
);
upsert_entities_fn!(
    upsert_users,
    "Upsert fetched users into the `users` table, so a team-membership join resolves names.",
    EntityTable::Users,
    types::User
);

/// Run a registered `(id, name)`-shaped `SELECT` -- the shared shape behind
/// [`query_teams`] and the team-scoped queries generated by
/// `query_team_scoped_fn!` below.
fn query_id_name_rows(
    conn: &Connection,
    stmt_sql: Sql,
    params: impl rusqlite::Params,
) -> Result<Vec<(String, String)>> {
    let mut stmt =
        sql::prepare(conn, stmt_sql).context("failed to prepare id/name query statement")?;
    let rows = stmt
        .query_map(params, |row| Ok((row.get("id")?, row.get("name")?)))
        .context("failed to execute id/name query")?;
    let mut out = Vec::new();
    for row in rows {
        out.push(row.context("failed to read id/name row")?);
    }
    Ok(out)
}

/// Every team, alphabetically by name.
pub fn query_teams(conn: &Connection) -> Result<Vec<types::Team>> {
    Ok(query_id_name_rows(conn, sql::QUERY_TEAMS, [])?
        .into_iter()
        .map(|(id, name)| types::Team {
            id: id.into(),
            name,
        })
        .collect())
}

/// Generates `pub fn $fn_name(conn, team_id: &str) -> Result<Vec<$ty>>`, a
/// team-scoped `(id, name)` query. A declarative macro rather than a shared
/// generic helper, so the near-identical typed wrapper ([`query_team_members`])
/// doesn't trip `cargo dupes`.
macro_rules! query_team_scoped_fn {
    // `$ty` is an `ident` fragment (not `ty`/`path`): those fragments are
    // captured as opaque, already-parsed nodes that a following `{` cannot
    // graft onto for a struct literal; a bare `ident` stays reparseable.
    ($fn_name:ident, $doc:expr, $sql:expr, $ty:ident) => {
        #[doc = $doc]
        pub fn $fn_name(conn: &Connection, team_id: &str) -> Result<Vec<$ty>> {
            Ok(query_id_name_rows(conn, $sql, params![team_id])?
                .into_iter()
                .map(|(id, name)| $ty {
                    id: id.into(),
                    name,
                })
                .collect())
        }
    };
}

query_team_scoped_fn!(
    query_team_members,
    "A team's members, resolved through `team_memberships`, by name.",
    sql::QUERY_TEAM_MEMBERS,
    User
);

/// A team's workflow states with Linear's stored `position`, in Linear's
/// stored order.
pub fn query_team_states(conn: &Connection, team_id: &str) -> Result<Vec<WorkflowState>> {
    crate::db::query_rows_id_name_and(
        conn,
        (sql::QUERY_TEAM_STATES, "position"),
        params![team_id],
        |id, name, position| WorkflowState {
            id: id.into(),
            name,
            position,
        },
    )
}

/// Replace a team's membership set with `user_ids`: delete then insert in one
/// transaction, so a member no longer on the team is removed rather than left
/// stale.
pub fn replace_team_memberships(conn: &Connection, team_id: &str, user_ids: &[&str]) -> Result<()> {
    let tx = conn
        .unchecked_transaction()
        .context("failed to begin membership replace transaction")?;
    sql::execute(
        &tx,
        sql::DELETE_TEAM_MEMBERSHIPS_FOR_TEAM,
        params![team_id],
        "clear team memberships",
    )?;
    for user_id in user_ids {
        sql::execute(
            &tx,
            sql::INSERT_TEAM_MEMBERSHIP,
            params![team_id, user_id],
            "insert team membership",
        )?;
    }
    tx.commit().context("failed to commit membership replace")?;
    Ok(())
}

/// Derive `team_memberships` from the seeded issues' distinct team/assignee
/// and team/creator pairs (`lt sim`; ADR "Sim compatibility" -- there is no
/// real team-membership API to seed from offline).
pub fn derive_team_memberships_from_issues(conn: &Connection) -> Result<()> {
    sql::execute(
        conn,
        sql::DERIVE_TEAM_MEMBERSHIPS_FROM_ISSUES,
        [],
        "derive team memberships from issues",
    )
}

impl Query for TeamsQuery {
    fn query(conn: &Connection, _vars: &Self::Variables) -> Result<Self::Output> {
        Ok(TeamConnection {
            nodes: query_teams(conn)?,
        })
    }
}

impl Mutation for TeamsQuery {
    fn apply(conn: &Connection, _vars: &Self::Variables, out: &Self::Output) -> Result<()> {
        upsert_teams(conn, &out.nodes)
    }
}

/// A team-scoped picker connection: the state/member picker queries share
/// this fetch-then-wrap shape, so their `Query::query` impls delegate to one
/// generic body ([`team_scoped_query`]) instead of colliding as duplicate
/// trait methods.
trait TeamScopedConnection: Sized {
    type Node;

    fn fetch(conn: &Connection, team_id: &str) -> Result<Vec<Self::Node>>;
    fn build(nodes: Vec<Self::Node>) -> Self;
}

fn team_scoped_query<C: TeamScopedConnection>(conn: &Connection, team_id: &str) -> Result<C> {
    Ok(C::build(C::fetch(conn, team_id)?))
}

impl TeamScopedConnection for WorkflowStateConnection {
    type Node = WorkflowState;

    fn fetch(conn: &Connection, team_id: &str) -> Result<Vec<WorkflowState>> {
        query_team_states(conn, team_id)
    }

    fn build(nodes: Vec<WorkflowState>) -> Self {
        Self { nodes }
    }
}

impl TeamScopedConnection for UserConnection {
    type Node = User;

    fn fetch(conn: &Connection, team_id: &str) -> Result<Vec<User>> {
        query_team_members(conn, team_id)
    }

    fn build(nodes: Vec<User>) -> Self {
        Self { nodes }
    }
}

impl Query for TeamStatesQuery {
    fn query(conn: &Connection, vars: &Self::Variables) -> Result<Self::Output> {
        team_scoped_query(conn, &vars.team_id)
    }
}

impl Mutation for TeamStatesQuery {
    /// The team id must come from the variables, not `out`: a `WorkflowState`
    /// carries only `{id, name, position}`, with no back-reference to its team.
    fn apply(conn: &Connection, vars: &Self::Variables, out: &Self::Output) -> Result<()> {
        for state in &out.nodes {
            upsert_team_state(conn, &vars.team_id, state)?;
        }
        Ok(())
    }
}

impl Mutation for AllWorkflowStatesQuery {
    /// Unlike [`TeamStatesQuery`], each node carries its own team id, so one
    /// page can span every team.
    fn apply(conn: &Connection, _vars: &Self::Variables, out: &Self::Output) -> Result<()> {
        for state in &out.nodes {
            let team_id = state.team.id.inner();
            upsert_team_state(
                conn,
                team_id,
                &WorkflowState {
                    id: state.id.clone(),
                    name: state.name.clone(),
                    position: state.position,
                },
            )?;
        }
        Ok(())
    }
}

impl Query for TeamMembersQuery {
    fn query(conn: &Connection, vars: &Self::Variables) -> Result<Self::Output> {
        team_scoped_query(conn, &vars.team_id)
    }
}

impl Mutation for TeamMembersQuery {
    /// Replace-set semantics preserved: users are upserted, then the team's
    /// membership rows are replaced wholesale so a member no longer on the
    /// team is dropped rather than left stale.
    fn apply(conn: &Connection, vars: &Self::Variables, out: &Self::Output) -> Result<()> {
        upsert_users(conn, &out.nodes)?;
        let member_ids: Vec<&str> = out.nodes.iter().map(|u| u.id.inner()).collect();
        replace_team_memberships(conn, &vars.team_id, &member_ids)
    }
}

impl Query for NewIssueQuery {
    fn query(conn: &Connection, vars: &Self::Variables) -> Result<Self::Output> {
        let teams = query_teams(conn)?;
        let (states, members) = if vars.has_team {
            (
                query_team_states(conn, &vars.team_id)?,
                query_team_members(conn, &vars.team_id)?,
            )
        } else {
            (Vec::new(), Vec::new())
        };
        let viewer = crate::db::viewer::viewer(conn)?;
        Ok(NewIssueData {
            teams,
            states,
            members,
            viewer,
        })
    }
}

impl Mutation for NewIssueQuery {
    /// `out.viewer` is never persisted here: it is always `None` from the
    /// wire (`NewIssueQuery`'s document does not select it, see
    /// `lt_types::new_issue`), and the display value is sourced from the
    /// cache via `Query` instead.
    fn apply(conn: &Connection, vars: &Self::Variables, out: &Self::Output) -> Result<()> {
        upsert_teams(conn, &out.teams)?;
        if vars.has_team {
            for state in &out.states {
                upsert_team_state(conn, &vars.team_id, state)?;
            }
            upsert_users(conn, &out.members)?;
            let member_ids: Vec<&str> = out.members.iter().map(|u| u.id.inner()).collect();
            replace_team_memberships(conn, &vars.team_id, &member_ids)?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use lt_types::members::TeamVariables as MembersTeamVariables;
    use lt_types::states::TeamVariables as StatesTeamVariables;

    use super::*;
    use crate::db::outbox;

    fn test_db() -> Connection {
        let db = crate::db::Database::memory().unwrap();
        db.connect().unwrap()
    }

    /// `state` is `(id, name, position)`, grouped so the helper stays under
    /// clippy's `too-many-arguments` threshold.
    fn upsert_state(conn: &Connection, team_id: &str, state: (&str, &str, f64)) {
        let (id, name, position) = state;
        upsert_team_state(
            conn,
            team_id,
            &WorkflowState {
                id: id.into(),
                name: name.to_string(),
                position,
            },
        )
        .unwrap();
    }

    #[test]
    fn query_teams_returns_alphabetical() {
        let conn = test_db();
        upsert_teams(
            &conn,
            &[
                types::Team {
                    id: "z".into(),
                    name: "Zulu".to_string(),
                },
                types::Team {
                    id: "a".into(),
                    name: "Alpha".to_string(),
                },
            ],
        )
        .unwrap();
        let teams = query_teams(&conn).unwrap();
        assert_eq!(
            teams.iter().map(|t| t.name.as_str()).collect::<Vec<_>>(),
            ["Alpha", "Zulu"]
        );
    }

    #[test]
    fn query_team_states_orders_by_position_then_name() {
        let conn = test_db();
        upsert_state(&conn, "t1", ("s-todo", "Todo", 1.0));
        upsert_state(&conn, "t1", ("s-done", "Done", 2.0));
        // Equal position: tie-broken by name.
        upsert_state(&conn, "t1", ("s-zeta", "Zeta", 3.0));
        upsert_state(&conn, "t1", ("s-alpha", "Alpha", 3.0));
        // A different team's state must not leak in.
        upsert_state(&conn, "t2", ("s-other", "Other", 0.5));

        let states = query_team_states(&conn, "t1").unwrap();
        assert_eq!(
            states.iter().map(|s| s.name.as_str()).collect::<Vec<_>>(),
            ["Todo", "Done", "Alpha", "Zeta"]
        );
    }

    #[test]
    fn scoped_upsert_overwrites_position_with_the_latest_write() {
        let conn = test_db();
        upsert_state(&conn, "t1", ("s1", "Todo", 3.5));
        // A later upsert of the same state (e.g. Linear reordered it) replaces
        // the position outright -- no merge against the stored value.
        upsert_state(&conn, "t1", ("s1", "Todo", 4.5));

        let position: f64 = conn
            .query_row(
                "SELECT position FROM workflow_states WHERE id = 's1'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(position.to_bits(), 4.5_f64.to_bits());
    }

    #[test]
    fn replace_team_memberships_is_replace_set() {
        let conn = test_db();
        upsert_users(
            &conn,
            &[
                types::User {
                    id: "u1".into(),
                    name: "Ada".to_string(),
                },
                types::User {
                    id: "u2".into(),
                    name: "Grace".to_string(),
                },
            ],
        )
        .unwrap();

        replace_team_memberships(&conn, "t1", &["u1", "u2"]).unwrap();
        let members = query_team_members(&conn, "t1").unwrap();
        assert_eq!(
            members.iter().map(|u| u.name.as_str()).collect::<Vec<_>>(),
            ["Ada", "Grace"]
        );

        // A second sync with a smaller set drops the removed member instead
        // of leaving it stale.
        replace_team_memberships(&conn, "t1", &["u1"]).unwrap();
        let members = query_team_members(&conn, "t1").unwrap();
        assert_eq!(
            members.iter().map(|u| u.name.as_str()).collect::<Vec<_>>(),
            ["Ada"]
        );
    }

    #[test]
    fn derive_team_memberships_from_issues_covers_assignee_and_creator() {
        let conn = test_db();
        let mut issue = outbox::sample_base_issue("1");
        issue.team = types::Team {
            id: "ENG".into(),
            name: "Engineering".to_string(),
        };
        issue.assignee = Some(types::User {
            id: "u-assignee".into(),
            name: "Assignee".to_string(),
        });
        issue.creator = Some(types::User {
            id: "u-creator".into(),
            name: "Creator".to_string(),
        });
        crate::db::upsert_issues(&conn, &[issue]).unwrap();

        derive_team_memberships_from_issues(&conn).unwrap();

        let members = query_team_members(&conn, "ENG").unwrap();
        let mut names: Vec<&str> = members.iter().map(|u| u.name.as_str()).collect();
        names.sort_unstable();
        assert_eq!(names, ["Assignee", "Creator"]);
    }

    #[test]
    fn teams_query_apply_writes_teams() {
        let conn = test_db();
        let teams = TeamConnection {
            nodes: vec![types::Team {
                id: "t1".into(),
                name: "Eng".to_string(),
            }],
        };
        TeamsQuery::apply(&conn, &(), &teams).unwrap();
        assert_eq!(query_teams(&conn).unwrap()[0].name, "Eng");
    }

    #[test]
    fn team_states_query_read_preserves_position_order() {
        let conn = test_db();
        upsert_state(&conn, "t1", ("s-todo", "Todo", 1.0));
        upsert_state(&conn, "t1", ("s-zeta", "Zeta", 2.0));

        let vars = StatesTeamVariables {
            team_id: "t1".to_string(),
        };
        let states = TeamStatesQuery::query(&conn, &vars).unwrap();
        assert_eq!(
            states
                .nodes
                .iter()
                .map(|s| (s.name.as_str(), s.position))
                .collect::<Vec<_>>(),
            [("Todo", 1.0), ("Zeta", 2.0)]
        );
    }

    #[test]
    fn team_states_query_apply_writes_positions() {
        let conn = test_db();
        let vars = StatesTeamVariables {
            team_id: "t1".to_string(),
        };
        let out = WorkflowStateConnection {
            nodes: vec![WorkflowState {
                id: "s1".into(),
                name: "Todo".to_string(),
                position: 1.0,
            }],
        };
        TeamStatesQuery::apply(&conn, &vars, &out).unwrap();
        let states = query_team_states(&conn, "t1").unwrap();
        assert_eq!(states[0].name, "Todo");
    }

    #[test]
    fn all_workflow_states_query_apply_scopes_each_state_to_its_own_team() {
        use lt_types::states::{
            AllWorkflowStatesVariables, TeamRef, WorkflowStateWithTeam,
            WorkflowStateWithTeamConnection,
        };

        let conn = test_db();
        let out = WorkflowStateWithTeamConnection {
            nodes: vec![
                WorkflowStateWithTeam {
                    id: "s1".into(),
                    name: "Todo".to_string(),
                    position: 1.0,
                    team: TeamRef { id: "t1".into() },
                },
                WorkflowStateWithTeam {
                    id: "s2".into(),
                    name: "Done".to_string(),
                    position: 2.0,
                    team: TeamRef { id: "t1".into() },
                },
                WorkflowStateWithTeam {
                    id: "s3".into(),
                    name: "Backlog".to_string(),
                    position: 1.0,
                    team: TeamRef { id: "t2".into() },
                },
            ],
            page_info: lt_types::pagination::PageInfo::default(),
        };

        let vars = AllWorkflowStatesVariables {
            first: 250,
            after: None,
        };
        lt_types::states::AllWorkflowStatesQuery::apply(&conn, &vars, &out).unwrap();

        let t1_states = query_team_states(&conn, "t1").unwrap();
        assert_eq!(
            t1_states
                .iter()
                .map(|s| s.name.as_str())
                .collect::<Vec<_>>(),
            ["Todo", "Done"]
        );
        let t2_states = query_team_states(&conn, "t2").unwrap();
        assert_eq!(t2_states[0].name, "Backlog");
    }

    #[test]
    fn team_members_query_apply_is_a_replace_set() {
        let conn = test_db();
        let vars = MembersTeamVariables {
            team_id: "t1".to_string(),
        };
        let first = UserConnection {
            nodes: vec![
                User {
                    id: "u1".into(),
                    name: "Ada".to_string(),
                },
                User {
                    id: "u2".into(),
                    name: "Grace".to_string(),
                },
            ],
        };
        TeamMembersQuery::apply(&conn, &vars, &first).unwrap();
        assert_eq!(query_team_members(&conn, "t1").unwrap().len(), 2);

        let second = UserConnection {
            nodes: vec![User {
                id: "u1".into(),
                name: "Ada".to_string(),
            }],
        };
        TeamMembersQuery::apply(&conn, &vars, &second).unwrap();
        assert_eq!(query_team_members(&conn, "t1").unwrap().len(), 1);
    }

    fn new_issue_vars(team_id: Option<&str>) -> lt_types::new_issue::NewIssueVariables {
        lt_types::new_issue::NewIssueVariables::new(team_id.map(str::to_string))
    }

    #[test]
    fn new_issue_query_read_without_a_team_leaves_states_and_members_empty() {
        let conn = test_db();
        upsert_teams(
            &conn,
            &[types::Team {
                id: "t1".into(),
                name: "Eng".to_string(),
            }],
        )
        .unwrap();

        let data = NewIssueQuery::query(&conn, &new_issue_vars(None)).unwrap();
        assert_eq!(data.teams.len(), 1);
        assert!(data.states.is_empty());
        assert!(data.members.is_empty());
        assert!(data.viewer.is_none());
    }

    #[test]
    fn new_issue_query_read_with_a_team_includes_its_states_and_members() {
        let conn = test_db();
        upsert_state(&conn, "t1", ("s1", "Todo", 1.0));
        upsert_users(
            &conn,
            &[User {
                id: "u1".into(),
                name: "Ada".to_string(),
            }],
        )
        .unwrap();
        replace_team_memberships(&conn, "t1", &["u1"]).unwrap();

        let data = NewIssueQuery::query(&conn, &new_issue_vars(Some("t1"))).unwrap();
        assert_eq!(data.states.len(), 1);
        assert_eq!(data.members.len(), 1);
    }

    #[test]
    fn new_issue_query_apply_writes_teams_and_team_scoped_data() {
        let conn = test_db();
        let vars = new_issue_vars(Some("t1"));
        let out = NewIssueData {
            teams: vec![types::Team {
                id: "t1".into(),
                name: "Eng".to_string(),
            }],
            states: vec![WorkflowState {
                id: "s1".into(),
                name: "Todo".to_string(),
                position: 1.0,
            }],
            members: vec![User {
                id: "u1".into(),
                name: "Ada".to_string(),
            }],
            viewer: None,
        };
        NewIssueQuery::apply(&conn, &vars, &out).unwrap();
        assert_eq!(query_teams(&conn).unwrap()[0].name, "Eng");
        assert_eq!(query_team_states(&conn, "t1").unwrap()[0].name, "Todo");
        assert_eq!(query_team_members(&conn, "t1").unwrap()[0].name, "Ada");
    }

    #[test]
    fn new_issue_query_apply_without_a_team_only_writes_teams() {
        let conn = test_db();
        let vars = new_issue_vars(None);
        let out = NewIssueData {
            teams: vec![types::Team {
                id: "t1".into(),
                name: "Eng".to_string(),
            }],
            states: Vec::new(),
            members: Vec::new(),
            viewer: None,
        };
        NewIssueQuery::apply(&conn, &vars, &out).unwrap();
        assert_eq!(query_teams(&conn).unwrap()[0].name, "Eng");
        assert!(query_team_states(&conn, "t1").unwrap().is_empty());
        assert!(query_team_members(&conn, "t1").unwrap().is_empty());
    }
}
