//! Team metadata: the team list, a team's workflow states (Linear's stored
//! `position` order), and its memberships. `workflow_states` is scoped for
//! free by every issue upsert (`db::issues::upsert_issue_tx`); only a
//! targeted team refresh ([`TeamStatesQuery`]'s and [`TeamMembersQuery`]'s
//! `Upsert` impls) writes memberships and positions.

use anyhow::{Context, Result};
use lt_types::members::TeamMembersQuery;
use lt_types::states::{TeamStatesQuery, WorkflowStateWithPosition};
use lt_types::teams::TeamsQuery;
use lt_types::types;
use lt_types::types::{User, WorkflowState};
use rusqlite::{Connection, params};

use crate::db::ops::{EntityKey, Read, Upsert};
use crate::db::sql::{self, EntityTable, Sql};

/// Upsert one workflow state scoped to its team, with Linear's stored
/// position (a targeted team sync -- the only writer that knows it).
pub fn upsert_team_state(
    conn: &Connection,
    team_id: &str,
    state: &WorkflowStateWithPosition,
) -> Result<()> {
    sql::execute(
        conn,
        sql::UPSERT_WORKFLOW_STATE_SCOPED,
        params![state.id.inner(), state.name, team_id, state.position],
        "upsert team-scoped workflow state",
    )
}

/// Back-fill a workflow state's `team_id` from an issue upsert, which knows
/// no position. Binds `UPSERT_WORKFLOW_STATE_SCOPED` directly with a SQL
/// `NULL` position; its `COALESCE` keeps a position already recorded by a
/// targeted team sync (see [`upsert_team_state`]).
pub(crate) fn upsert_workflow_state_team_only(
    conn: &Connection,
    id: &str,
    name: &str,
    team_id: &str,
) -> Result<()> {
    sql::execute(
        conn,
        sql::UPSERT_WORKFLOW_STATE_SCOPED,
        params![id, name, team_id, Option::<f64>::None],
        "upsert workflow state team-only",
    )
}

/// Generates `pub fn $fn_name(conn, entities: &[$ty]) -> Result<()>`,
/// upserting each entity's `(id, name)` into `$table`. A declarative macro
/// rather than a shared generic helper, so the near-identical typed wrappers
/// ([`upsert_teams`], [`upsert_users`]) don't trip `cargo dupes` -- the same
/// reason `sql::entity_upsert_sql!` exists.
macro_rules! upsert_entities_fn {
    ($fn_name:ident, $doc:expr, $table:expr, $ty:ty) => {
        #[doc = $doc]
        pub fn $fn_name(conn: &Connection, entities: &[$ty]) -> Result<()> {
            for entity in entities {
                crate::db::issues::upsert_named_entity(
                    conn,
                    $table,
                    entity.id.inner(),
                    Some(&entity.name),
                )?;
            }
            Ok(())
        }
    };
}

upsert_entities_fn!(
    upsert_teams,
    "Upsert fetched teams into the `teams` table.",
    EntityTable::Teams,
    types::Team
);
upsert_entities_fn!(
    upsert_users,
    "Upsert fetched users into the `users` table, so a team-membership join resolves names.",
    EntityTable::Users,
    types::User
);

/// Run a registered `(id, name)`-shaped `SELECT` -- the shared shape behind
/// [`query_teams`] and the team-scoped queries generated by
/// `query_team_scoped_fn!` below.
fn query_id_name_rows(
    conn: &Connection,
    stmt_sql: Sql,
    params: impl rusqlite::Params,
) -> Result<Vec<(String, String)>> {
    let mut stmt =
        sql::prepare(conn, stmt_sql).context("failed to prepare id/name query statement")?;
    let rows = stmt
        .query_map(params, |row| Ok((row.get("id")?, row.get("name")?)))
        .context("failed to execute id/name query")?;
    let mut out = Vec::new();
    for row in rows {
        out.push(row.context("failed to read id/name row")?);
    }
    Ok(out)
}

/// Every team, alphabetically by name.
pub fn query_teams(conn: &Connection) -> Result<Vec<types::Team>> {
    Ok(query_id_name_rows(conn, sql::QUERY_TEAMS, [])?
        .into_iter()
        .map(|(id, name)| types::Team {
            id: id.into(),
            name,
        })
        .collect())
}

/// Generates `pub fn $fn_name(conn, team_id: &str) -> Result<Vec<$ty>>`, a
/// team-scoped `(id, name)` query. A declarative macro rather than a shared
/// generic helper, so the near-identical typed wrappers ([`query_team_states`],
/// [`query_team_members`]) don't trip `cargo dupes`.
macro_rules! query_team_scoped_fn {
    // `$ty` is an `ident` fragment (not `ty`/`path`): those fragments are
    // captured as opaque, already-parsed nodes that a following `{` cannot
    // graft onto for a struct literal; a bare `ident` stays reparseable.
    ($fn_name:ident, $doc:expr, $sql:expr, $ty:ident) => {
        #[doc = $doc]
        pub fn $fn_name(conn: &Connection, team_id: &str) -> Result<Vec<$ty>> {
            Ok(query_id_name_rows(conn, $sql, params![team_id])?
                .into_iter()
                .map(|(id, name)| $ty {
                    id: id.into(),
                    name,
                })
                .collect())
        }
    };
}

query_team_scoped_fn!(
    query_team_states,
    "A team's workflow states, Linear's stored `position` order first; states known only from issue upserts (`position IS NULL`) sort last, by name.",
    sql::QUERY_TEAM_STATES,
    WorkflowState
);
query_team_scoped_fn!(
    query_team_members,
    "A team's members, resolved through `team_memberships`, by name.",
    sql::QUERY_TEAM_MEMBERS,
    User
);

/// A team's workflow states with Linear's stored `position`, in the same
/// order as [`query_team_states`]. A state known only from an issue upsert
/// (`position IS NULL`) maps to `f64::MAX` so it keeps sorting last, matching
/// the SQL `ORDER BY position IS NULL, position, name`.
fn query_team_states_with_position(
    conn: &Connection,
    team_id: &str,
) -> Result<Vec<WorkflowStateWithPosition>> {
    let mut stmt = sql::prepare(conn, sql::QUERY_TEAM_STATES_WITH_POSITION)
        .context("failed to prepare team states (with position) query statement")?;
    let rows = stmt
        .query_map(params![team_id], |row| {
            let position: Option<f64> = row.get("position")?;
            Ok(WorkflowStateWithPosition {
                id: row.get::<_, String>("id")?.into(),
                name: row.get("name")?,
                position: position.unwrap_or(f64::MAX),
            })
        })
        .context("failed to execute team states (with position) query")?;
    let mut out = Vec::new();
    for row in rows {
        out.push(row.context("failed to read team state (with position) row")?);
    }
    Ok(out)
}

/// Replace a team's membership set with `user_ids`: delete then insert in one
/// transaction, so a member no longer on the team is removed rather than left
/// stale.
pub fn replace_team_memberships(conn: &Connection, team_id: &str, user_ids: &[&str]) -> Result<()> {
    let tx = conn
        .unchecked_transaction()
        .context("failed to begin membership replace transaction")?;
    sql::execute(
        &tx,
        sql::DELETE_TEAM_MEMBERSHIPS_FOR_TEAM,
        params![team_id],
        "clear team memberships",
    )?;
    for user_id in user_ids {
        sql::execute(
            &tx,
            sql::INSERT_TEAM_MEMBERSHIP,
            params![team_id, user_id],
            "insert team membership",
        )?;
    }
    tx.commit().context("failed to commit membership replace")?;
    Ok(())
}

/// Derive `team_memberships` from the seeded issues' distinct team/assignee
/// and team/creator pairs (`lt sim`; ADR "Sim compatibility" -- there is no
/// real team-membership API to seed from offline).
pub fn derive_team_memberships_from_issues(conn: &Connection) -> Result<()> {
    sql::execute(
        conn,
        sql::DERIVE_TEAM_MEMBERSHIPS_FROM_ISSUES,
        [],
        "derive team memberships from issues",
    )
}

impl Read for TeamsQuery {
    fn read(conn: &Connection, _vars: &Self::Variables) -> Result<Self::Output> {
        query_teams(conn)
    }

    fn reads(_vars: &Self::Variables) -> Vec<EntityKey> {
        vec![EntityKey::Teams]
    }
}

impl Upsert for TeamsQuery {
    fn upsert(
        conn: &Connection,
        _vars: &Self::Variables,
        out: &Self::Output,
    ) -> Result<Vec<EntityKey>> {
        upsert_teams(conn, out)?;
        Ok(vec![EntityKey::Teams])
    }
}

impl Read for TeamStatesQuery {
    fn read(conn: &Connection, vars: &Self::Variables) -> Result<Self::Output> {
        query_team_states_with_position(conn, &vars.team_id)
    }

    fn reads(vars: &Self::Variables) -> Vec<EntityKey> {
        vec![EntityKey::WorkflowStates {
            team_id: vars.team_id.clone(),
        }]
    }
}

impl Upsert for TeamStatesQuery {
    /// The team id must come from the variables, not `out`: a positioned
    /// state carries only `{id, name, position}`, with no back-reference to
    /// its team.
    fn upsert(
        conn: &Connection,
        vars: &Self::Variables,
        out: &Self::Output,
    ) -> Result<Vec<EntityKey>> {
        for state in out {
            upsert_team_state(conn, &vars.team_id, state)?;
        }
        Ok(vec![EntityKey::WorkflowStates {
            team_id: vars.team_id.clone(),
        }])
    }
}

impl Read for TeamMembersQuery {
    fn read(conn: &Connection, vars: &Self::Variables) -> Result<Self::Output> {
        query_team_members(conn, &vars.team_id)
    }

    fn reads(vars: &Self::Variables) -> Vec<EntityKey> {
        vec![EntityKey::TeamMemberships {
            team_id: vars.team_id.clone(),
        }]
    }
}

impl Upsert for TeamMembersQuery {
    /// Replace-set semantics preserved: users are upserted, then the team's
    /// membership rows are replaced wholesale so a member no longer on the
    /// team is dropped rather than left stale.
    fn upsert(
        conn: &Connection,
        vars: &Self::Variables,
        out: &Self::Output,
    ) -> Result<Vec<EntityKey>> {
        upsert_users(conn, out)?;
        let member_ids: Vec<&str> = out.iter().map(|u| u.id.inner()).collect();
        replace_team_memberships(conn, &vars.team_id, &member_ids)?;
        Ok(vec![EntityKey::TeamMemberships {
            team_id: vars.team_id.clone(),
        }])
    }
}

#[cfg(test)]
mod tests {
    use lt_types::members::TeamVariables as MembersTeamVariables;
    use lt_types::states::TeamVariables as StatesTeamVariables;

    use super::*;
    use crate::db::outbox;

    fn test_db() -> Connection {
        let db = crate::db::Database::memory().unwrap();
        db.connect().unwrap()
    }

    /// `state` is `(id, name, position)`, grouped so the helper stays under
    /// clippy's `too-many-arguments` threshold.
    fn upsert_state(conn: &Connection, team_id: &str, state: (&str, &str, f64)) {
        let (id, name, position) = state;
        upsert_team_state(
            conn,
            team_id,
            &WorkflowStateWithPosition {
                id: id.into(),
                name: name.to_string(),
                position,
            },
        )
        .unwrap();
    }

    #[test]
    fn query_teams_returns_alphabetical() {
        let conn = test_db();
        upsert_teams(
            &conn,
            &[
                types::Team {
                    id: "z".into(),
                    name: "Zulu".to_string(),
                },
                types::Team {
                    id: "a".into(),
                    name: "Alpha".to_string(),
                },
            ],
        )
        .unwrap();
        let teams = query_teams(&conn).unwrap();
        assert_eq!(
            teams.iter().map(|t| t.name.as_str()).collect::<Vec<_>>(),
            ["Alpha", "Zulu"]
        );
    }

    #[test]
    fn query_team_states_orders_by_position_then_nulls_last_by_name() {
        let conn = test_db();
        upsert_state(&conn, "t1", ("s-todo", "Todo", 1.0));
        upsert_state(&conn, "t1", ("s-done", "Done", 2.0));
        // No position recorded yet -- an issue-driven upsert only.
        upsert_workflow_state_team_only(&conn, "s-zeta", "Zeta", "t1").unwrap();
        upsert_workflow_state_team_only(&conn, "s-alpha", "Alpha", "t1").unwrap();
        // A different team's state must not leak in.
        upsert_state(&conn, "t2", ("s-other", "Other", 0.5));

        let states = query_team_states(&conn, "t1").unwrap();
        assert_eq!(
            states.iter().map(|s| s.name.as_str()).collect::<Vec<_>>(),
            ["Todo", "Done", "Alpha", "Zeta"]
        );
    }

    #[test]
    fn scoped_upsert_backfills_team_id_without_clobbering_position() {
        let conn = test_db();
        // A targeted team sync records a real position.
        upsert_state(&conn, "t1", ("s1", "Todo", 3.5));
        // An issue-driven upsert passes NULL and must not clobber it.
        upsert_workflow_state_team_only(&conn, "s1", "Todo", "t1").unwrap();

        let position: Option<f64> = conn
            .query_row(
                "SELECT position FROM workflow_states WHERE id = 's1'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(position, Some(3.5));
    }

    #[test]
    fn issue_upsert_backfills_team_id() {
        let conn = test_db();
        crate::db::upsert_issues(&conn, &[outbox::sample_base_issue("1")]).unwrap();

        let (team_id, position): (Option<String>, Option<f64>) = conn
            .query_row(
                "SELECT team_id, position FROM workflow_states WHERE id = \
                 (SELECT state_id FROM issues WHERE id = '1')",
                [],
                |r| Ok((r.get(0)?, r.get(1)?)),
            )
            .unwrap();
        assert!(team_id.is_some());
        assert_eq!(position, None);
    }

    #[test]
    fn replace_team_memberships_is_replace_set() {
        let conn = test_db();
        upsert_users(
            &conn,
            &[
                types::User {
                    id: "u1".into(),
                    name: "Ada".to_string(),
                },
                types::User {
                    id: "u2".into(),
                    name: "Grace".to_string(),
                },
            ],
        )
        .unwrap();

        replace_team_memberships(&conn, "t1", &["u1", "u2"]).unwrap();
        let members = query_team_members(&conn, "t1").unwrap();
        assert_eq!(
            members.iter().map(|u| u.name.as_str()).collect::<Vec<_>>(),
            ["Ada", "Grace"]
        );

        // A second sync with a smaller set drops the removed member instead
        // of leaving it stale.
        replace_team_memberships(&conn, "t1", &["u1"]).unwrap();
        let members = query_team_members(&conn, "t1").unwrap();
        assert_eq!(
            members.iter().map(|u| u.name.as_str()).collect::<Vec<_>>(),
            ["Ada"]
        );
    }

    #[test]
    fn derive_team_memberships_from_issues_covers_assignee_and_creator() {
        let conn = test_db();
        let mut issue = outbox::sample_base_issue("1");
        issue.team = types::Team {
            id: "ENG".into(),
            name: "Engineering".to_string(),
        };
        issue.assignee = Some(types::User {
            id: "u-assignee".into(),
            name: "Assignee".to_string(),
        });
        issue.creator = Some(types::User {
            id: "u-creator".into(),
            name: "Creator".to_string(),
        });
        crate::db::upsert_issues(&conn, &[issue]).unwrap();

        derive_team_memberships_from_issues(&conn).unwrap();

        let members = query_team_members(&conn, "ENG").unwrap();
        let mut names: Vec<&str> = members.iter().map(|u| u.name.as_str()).collect();
        names.sort_unstable();
        assert_eq!(names, ["Assignee", "Creator"]);
    }

    #[test]
    fn teams_query_reads_only_the_teams_key() {
        assert_eq!(TeamsQuery::reads(&()), vec![EntityKey::Teams]);
    }

    #[test]
    fn teams_query_upsert_writes_and_reports_teams() {
        let conn = test_db();
        let teams = vec![types::Team {
            id: "t1".into(),
            name: "Eng".to_string(),
        }];
        let touched = TeamsQuery::upsert(&conn, &(), &teams).unwrap();
        assert_eq!(touched, vec![EntityKey::Teams]);
        assert_eq!(query_teams(&conn).unwrap()[0].name, "Eng");
    }

    #[test]
    fn team_states_query_read_maps_null_position_to_f64_max_and_preserves_order() {
        let conn = test_db();
        upsert_state(&conn, "t1", ("s-todo", "Todo", 1.0));
        upsert_workflow_state_team_only(&conn, "s-zeta", "Zeta", "t1").unwrap();

        let vars = StatesTeamVariables {
            team_id: "t1".to_string(),
        };
        let states = TeamStatesQuery::read(&conn, &vars).unwrap();
        assert_eq!(
            states
                .iter()
                .map(|s| (s.name.as_str(), s.position))
                .collect::<Vec<_>>(),
            [("Todo", 1.0), ("Zeta", f64::MAX)]
        );
    }

    #[test]
    fn team_states_query_reads_the_team_id_in_variables() {
        let vars = StatesTeamVariables {
            team_id: "t1".to_string(),
        };
        assert_eq!(
            TeamStatesQuery::reads(&vars),
            vec![EntityKey::WorkflowStates {
                team_id: "t1".to_string()
            }]
        );
    }

    #[test]
    fn team_states_query_upsert_writes_positions_and_reports_the_team() {
        let conn = test_db();
        let vars = StatesTeamVariables {
            team_id: "t1".to_string(),
        };
        let out = vec![WorkflowStateWithPosition {
            id: "s1".into(),
            name: "Todo".to_string(),
            position: 1.0,
        }];
        let touched = TeamStatesQuery::upsert(&conn, &vars, &out).unwrap();
        assert_eq!(
            touched,
            vec![EntityKey::WorkflowStates {
                team_id: "t1".to_string()
            }]
        );
        let states = query_team_states(&conn, "t1").unwrap();
        assert_eq!(states[0].name, "Todo");
    }

    #[test]
    fn team_members_query_reads_the_team_id_in_variables() {
        let vars = MembersTeamVariables {
            team_id: "t1".to_string(),
        };
        assert_eq!(
            TeamMembersQuery::reads(&vars),
            vec![EntityKey::TeamMemberships {
                team_id: "t1".to_string()
            }]
        );
    }

    #[test]
    fn team_members_query_upsert_is_a_replace_set_and_reports_the_team() {
        let conn = test_db();
        let vars = MembersTeamVariables {
            team_id: "t1".to_string(),
        };
        let first = vec![
            User {
                id: "u1".into(),
                name: "Ada".to_string(),
            },
            User {
                id: "u2".into(),
                name: "Grace".to_string(),
            },
        ];
        let touched = TeamMembersQuery::upsert(&conn, &vars, &first).unwrap();
        assert_eq!(
            touched,
            vec![EntityKey::TeamMemberships {
                team_id: "t1".to_string()
            }]
        );
        assert_eq!(query_team_members(&conn, "t1").unwrap().len(), 2);

        let second = vec![User {
            id: "u1".into(),
            name: "Ada".to_string(),
        }];
        TeamMembersQuery::upsert(&conn, &vars, &second).unwrap();
        assert_eq!(query_team_members(&conn, "t1").unwrap().len(), 1);
    }
}
